# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/metadata-syntax-for-github-actions

name: 'NuGet Package Availability Checker'
description: >-
  GitHub Action automates NuGet package availability checks, ensuring packages exist and are indexed on nuget.org.
author: 'BMTLab'
branding:
  icon: package
  color: blue
inputs:
  package:
    description: 'NuGet package name to check (SomeCompany.PackageName e.g), case-insensitive'
    required: true
  version:
    description: 'Package version to check (2.3.4-preview e.g), case-insensitive'
    required: true
  attempts:
    description: 'Maximum number of attempts to check the package availability (10 e.g)'
    required: false
    default: '1'
outputs:
  indexed:
    description: 'Whether the package is indexed on nuget.org (true or false)'
runs:
  using: 'node20'
  main: 'dist/index.js'
