name: Git and GPG Setup
description: 'Set up GPG signed git bot'
inputs:
  name:
    description: 'GitHub Action Bot name'
    required: true
  email:
    description: 'GitHub bot email'
    required: false
    default: '41898282+github-actions[bot]@users.noreply.github.com'

runs:
  using: "composite"
  steps:
    - name: Import GPG key
      env:
        GPG_PRIVATE_KEY: ${{ env.GPG_PRIVATE_KEY }}
      run: |
        echo "$GPG_PRIVATE_KEY" | base64 --decode | gpg --batch --import
      shell: bash

    - name: Add the custom signing program that passes the passphrase to the GPG CLI
      run: |
        rm -rf /tmp/gpg.sh
        echo '#!/bin/bash' >> /tmp/gpg.sh
        echo 'gpg --batch --pinentry-mode=loopback --passphrase $GPG_PASSPHRASE $@' >> /tmp/gpg.sh
        chmod +x /tmp/gpg.sh
      shell: bash

    - name: Setup git
      env:
        GPG_KEY_ID: ${{ env.GPG_KEY_ID }}
      run: |
        git config commit.gpgsign true
        git config user.signingkey $GPG_KEY_ID
        git config gpg.program /tmp/gpg.sh
      shell: bash

